local icon_loc = "__Tiberian-Sun__/graphics/icons/item/"

data:extend({
-- STRUCTURES AVAILABLE TO BOTH
{
	type = "item",
	name = "ts-tiberium-refinery", 
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "004",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-tiberium-silo",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "010",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-emp-cannon",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "013",
	stack_size = 100,
},

-- GDI STRUCTURES
{
	type = "item",
	name = "ts-GDI-construction-yard",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "raw-material", -- change me!
	order = "001",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-power-plant",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "002",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-barracks",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "003",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-component-tower",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "005",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-concrete-walls",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "006",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-automatic-gate",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "007",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-war-factory",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "008",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-radar",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "009",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-service-depot",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "011",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-helipad",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "012",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-tech-center",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "014",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-upgrade-center",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "015",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-firestorm-generator",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "019",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-ion-cannon-upgrade",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "016",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-seeker-control",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "017",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-drop-pod-node",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "018",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-firestorm-wall",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "020",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-vulcan-cannon",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "021",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-rpg-upgrade",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "022",
	stack_size = 100,
},
{
	type = "item",
	name = "ts-GDI-sam-upgrade",
	icon = icon_loc .. "blank.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "energy",
	order = "023",
	stack_size = 100,
},
})